wp.blocks.registerBlockType("vbplugin/custom-block-type", {
  title: "Are You Paying Attention?",
  icon: "smiley",
  category: "common",
  attributes: {
    skyColour: { type: "string" },
    grassColour: { type: "string" },
  },
  // Code in post body
  edit: function (props) {
    function updateSkyColour(event) {
      props.setAttributes({ skyColour: event.target.value });
    }
    function updateGrassColour(event) {
      props.setAttributes({ grassColour: event.target.value });
    }
    return (
      <div>
        <input
          type="text"
          placeholder="sky colour"
          value={props.attributes.skyColour}
          onChange={updateSkyColour}
        />
        <input
          type="text"
          placeholder="grass colour"
          value={props.attributes.grassColour}
          onChange={updateGrassColour}
        />
      </div>
    );
  },
  // Code generated by save
  save: function (props) {
    return (
      <p>
        Today the sky is {props.attributes.skyColour} and the grass is{" "}
        {props.attributes.grassColour}
      </p>
    );
  },
});
